### PR TITLE
Roll Dart SDK

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
TBR @kwalrath

**Comment by kwalrath** [comment]
I think there's something else we're supposed to run to update the examples, isn't there? It's a little scary how many jobs failed.

**Comment by mit-mit** [comment]
I have no idea, honestly. We can roll-back if you think something is off?

**Comment by kwalrath** [comment]
I'm going to try to take a crack at this later this week.

/cc @alorenzen

**Pull request merged**
