### PR TITLE
Use stream_transform extension methods

### PR DESCRIPTION
**Pull request by natebosch**
Update examples to use the `1.0.0` version of `stream_transform` with
extension methods over calling `.transform(something)`. Bump minimum SDK
constraints to `2.6.0` in the pubspecs where the dependency was changed
to allow for using extension methods.

### CODE REVIEW

**Comment by natebosch** [comment]
Someone on gitter noticed that following the existing examples leads to a deprecation warning.

**Comment by kwalrath** [comment]
The build is failing on master (see https://travis-ci.org/dart-lang/site-angulardart) due to an out-of-date package, but this change has more failing tests that I haven't diagnosed.

**Comment by natebosch** [comment]
It looks like most of the failures are related to needing to update other packages like`build_runner`. I'm not sure what the process is for handling new package versions in this repo. There are a couple errors that might not be related to package versions, but I can't tell what the failure is.

https://travis-ci.org/dart-lang/site-angulardart/jobs/632485541?utm_medium=notification&utm_source=github_status

**Comment by kwalrath** [comment]
It seems questionable to break the build when a package updates... I'll talk to people about this tomorrow.

**Comment by natebosch** [comment]
There are other issues cropping up here, I think maybe a version constraint  can't be satisfied somewhere. Looks like I might need to get a new version of `build_runner` published.

**Comment by chalin** [comment]
I can take a quick look if you'd like.

**Comment by natebosch** [comment]
I found at least one problem I can solve, I'll let you know once I've got the `pub get` working in the `server_communication` package and we can check if there are other issues.

**Comment by chalin** [comment]
> It seems questionable to break the build when a package updates... 

The package version check made sense when the packages were evolving rapidly, which is no longer the case. #129 removes the check.

**Comment by natebosch** [comment]
I published a new `build_runner` and `build_daemon` which unblocks the version solve in `examples/ng/doc/server-communication`. Hopefully with that and a merge from master we get unblocked.

**Comment by natebosch** [comment]
Looks like another constraint conflict with `pageloader`. I'll try to chase that one down.

**Comment by natebosch** [comment]
I think blocked by https://github.com/google/pageloader/pull/203 currently.

**Comment by natebosch** [comment]
Hmm, the trickiness now is that the latest `pageloader` isn't compatible with angular `5.3.1` due to a dep on `analyzer`... That isn't likely to get fixed.

I'll see if it works to maybe lower the bound for `stream_transform`.

**Comment by kevmoo** [comment]
We're not super motivated to take updates to this site. Closing out.

**Pull request closed without merging**
