### PR TITLE
Make /api a static page and stop generating local API docs

### LINKED ISSUE #73: Stop generating local copy of API docs
Followup to #70

### LINKED ISSUE #75: API page should be a static page with links to API docs
- [ ] Replace the current AngularJS app in /api by static links
- [ ] Provide Firebase redirect rules if necessary and/or practical

### PR DESCRIPTION
**Pull request by chalin**
Followup to #74
Closes #73 
Closes #75

Staged at https://angulardart-org-dev2.firebaseapp.com/api

### CODE REVIEW

**Comment by johnpryan** [comment]
It looks like there's an issue with the angular_components docs: https://pub.dev/documentation/angular_components

**Comment by chalin** [comment]
Yes, it is a known issue. Hopefully the API docs will be generated at some point soon. I suppose that I could add a note in the meantime. WDYT?

**Comment by johnpryan** [comment]
Is there a working link we can use? Otherwise I would take it out for now.

**Comment by chalin** [comment]
I've added a link to the gallery as well, see the updated staging server:
> image

**Pull request merged**
